### ISSUE TITLE
UI goes to second challenge window & invalid redirectUri

### ISSUE THREAD

**Issue by scotthenninger** [aws-samples/amazon-cognito-passwordless-auth#141]
I have followed the workshop using Cloud9 and opening the UI through Preview Running Application.  I am first met with a challenge to Sign in with passkey or Enter an e-mail, as expected. If I use the e-mail option it takes me to another challenge window.  Is this expected behavior?  I would have expected the entered email address to receive an email with the magic link.

Secondly if I follow the second challenge window to Sign-in with magic link I get an Invalid redirectUri error message.  The invalid uri looks like https://67fc3ff145d745d2b32f69eb454f9f3d.vfs.cloud9.us-east-1.amazonaws.com/. Is there some place I should have set the redirect URI?

**Comment by ottokruse** [comment]
Hi @scotthenninger 

> If I use the e-mail option it takes me to another challenge window. Is this expected behavior?

Can't follow this exactly yet, can you share screen shots or a short video clip?

The UI did change a bit since the workshop was released so screen shots may be slightly outdated: you first enter your e-mail address now and then proceed to the 2nd screen where you have to click "sign in with magic link". Other than that it's all still the same.

> Is there some place I should have set the redirect URI?

When running the workshop:

- Make sure to set the right environment variables, following the instructions [here](https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US/15-prereqs/17-env-setup#environment-variables)
- Use the env var WS_PREVIEW_URL as allowed origin in the CDK construct: [link](https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US/20-backend/22-add-fido2#2.-add-the-passwordless-construct)

Hope that helps.

**Comment by scotthenninger** [comment]
Hello @ottokruse;

Thanks for the explanation on the UI - that is the behavior I'm seeing.  In terms of the invalid redirect I'm attaching the UI and a screen shot of the console.  The environment variables check out as stated in the workshop and the URL seems to be the same as the WS_PREVIEW_URL so I'm not entirely clear why the redirect error occurs.  Any hints or further suggestions would be appreciated.

And thanks!
![Screenshot 2024-01-22 at 4 42 09 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/861498/5a5ee5df-b992-4c4f-b0d5-48483fe18446)
![Screenshot 2024-01-22 at 4 37 45 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/861498/8e660244-7946-410a-8be1-239934db5352)

**Comment by ottokruse** [comment]
That error is thrown by backend code:

https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/d7dda2898e5bfe227a4c5e5c4a46b1a07a4d83aa/cdk/custom-auth/magic-link.ts#L116-L123

Can you double check that you used the `WS_PREVIEW_URL` as `allowedOrigin` when instantiating the CDK construct? Should be in this step: [link](https://catalog.workshops.aws/cognito-webauthn-passwordless/en-US/20-backend/22-add-fido2#2.-add-the-passwordless-construct)

If that looks good, try redeploying. You can also check the Lambda function in the AWS console, and verify that its environment variable `ALLOWED_ORIGINS` includes the value from `WS_PREVIEW_URL`  (https://67fc3ff145d745d2b32f69eb454f9f3d.vfs.cloud9.us-east-1.amazonaws.com)

**Comment by scotthenninger** [comment]
Thanks for all your help @ottokruse.  Either redeploying or setting WS_EMAIL (I had forgotten this step in my previous iteration) did the trick.

Thanks again for your help and for writing up this example!

**Comment by ottokruse** [comment]
Nice!
