### ISSUE TITLE
Type Error fido2GetCredential in Safari

### ISSUE THREAD

**Issue by juanfernandez-gh** [aws-samples/amazon-cognito-passwordless-auth#188]
Hi, I've integrated this lib and so far is working great for chrome and Firefox, but we are having issues with safari when getting the credentials because it is throwing a super ambiguous error (attached in the image) from the function `fido2GetCredential` in `fido2.js:214`, this is ```const credential = await navigator.credentials.get({
        publicKey,
    });``` I've confirmed that the publicKey object is the same in chrome and safari.

<img width="338" alt="Screenshot 2024-08-22 at 5 11 13 PM" src="https://github.com/user-attachments/assets/7cc52027-9b0b-4721-a48d-7f2419eb83ec">

**Comment by ottokruse** [comment]
Mmmmm doesn't ring a bell yet.

I'm a Safari 17.6, you?

What version of the Passwordless lib are you on?

Bread crumb: `const credential = await credentialsContainer?.get({ publicKey, });` that is not the code of this lib. You using a password manager or so that is injecting itself "transparantly"? Say 1Pasword?

**Comment by ottokruse** [comment]
Just saw this, try that? Set residentkey (can be set when you call Passwordless.configure on the front end)

https://stackoverflow.com/questions/75350756/getting-type-error-when-using-webauthn-on-ios

**Comment by ottokruse** [comment]
Which macOS / iOS version are you on ?

**Comment by ottokruse** [comment]
OK that should be good.

Tried [this](https://stackoverflow.com/a/75716701/1376848) yet?

```typescript
Passwordless.configure({
  cognitoIdpEndpoint: import.meta.env.VITE_COGNITO_IDP_ENDPOINT,
  clientId: import.meta.env.VITE_CLIENT_ID,
  fido2: {
    baseUrl: import.meta.env.VITE_FIDO2_BASE_URL,
   
    authenticatorSelection: {
      userVerification: "required",
      requireResidentKey: true, // added
      residentKey: "required", // added
    },
  },
  debug: console.debug,
});
```

**Comment by ottokruse** [comment]
`authenticatorSelection` is not a valid field for `navigator.credentials.get()`, see https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialrequestoptions.

It *is* a valid field for `navigator.credentials.create()`, see https://www.w3.org/TR/webauthn-2/#dictdef-publickeycredentialcreationoptions

What exactly is your situation? You can create the passkey, but not sign-in with it? Or the create already fails?

**Comment by ottokruse** [comment]
I just tried the end-to-end example again on Safari 17.6 (19618.3.11.11.5) on MacOS Sonoma 14.6.1 and it works like a charm for me, both for my Mac's touch as with a Yubikey.

That's with this config, unchanged per the end-to-end example:

```js
Passwordless.configure({
  cognitoIdpEndpoint: import.meta.env.VITE_COGNITO_IDP_ENDPOINT,
  clientId: import.meta.env.VITE_CLIENT_ID,
  fido2: {
    baseUrl: import.meta.env.VITE_FIDO2_BASE_URL,
    authenticatorSelection: {
      userVerification: "required",
    },
  },
  debug: console.debug,
});
```

Can you also try to deploy the [end-to-end example](https://github.com/aws-samples/amazon-cognito-passwordless-auth/tree/main/end-to-end-example) and try that one?

Otherwise send me your email address please I can add you to my instance as well as user. Then we can try you creating a passkey and logging in with that to my sample deployment and I can have a look in dynamodb at what's different between your fido credentials and mine.

**Comment by ottokruse** [comment]
Done, sent you an SES verification mail (please click the link) and then you can sign in here with a magic link, after which you can create a passkey and sign in with that: https://dgn579m3u5x3n.cloudfront.net/

**Comment by ottokruse** [comment]
I can't quickly find a source for this info but I remember safari has a quirk. Safari requires the webauthn API call to be made in an event directly triggered by the user, like a click. At which point and how are you invoking the Passwordless lib? In an onclick handler?

**Comment by ottokruse** [comment]
This post mentions it and I came across it myself as well earlier. https://www.linkedin.com/posts/timcappalli_introducing-passkey-support-to-fastmail-activity-7234553443154092032-1Y2T?utm_source=share&utm_medium=member_ios

**Comment by ottokruse** [comment]
Yes you can await the `authenticateWithFido2().signedIn` promise to get the error in your face bubbled up, or rely on the `lastError` variable in the hook.

**Comment by ottokruse** [comment]
Frustrating!

I have no ideas left at this point.

Suggest to try the Webauthn calls directly (`navigator.credentials.get()`) and see if that works. If not--file the issue with Apple against Safari. If that __does__ work, we'd need to figure out why our lib fails for you (but not in our own example, so weird!).

**Comment by ottokruse** [comment]
Any update mate?

**Comment by ottokruse** [comment]
Thanks for getting back ! Good news 🎉
