### ISSUE TITLE
Support for Office365 Safe Links

### ISSUE THREAD

**Issue by fortejas** [aws-samples/amazon-cognito-passwordless-auth#44]
Hi

I'm going through the documentation for this repo. One concern I have is around users who are using the [Office 365 Safe Links feature](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about). With this enabled the Safe Links system would access the magic link URL before the user does and therefore the link would always be invalid. 

Are there suggestions for a workaround or does this sample somehow already cater for this?

Any suggestions would be great thanks!

**Comment by ottokruse** [comment]
Does Office365 actually load the JS for that URL and start the React app? Because React will then use the URL fragment to init auth which you can only do once indeed. But just fetching the URL and not executing React should be no issue.

Otherwise, yes, a magic link can be used once only in this solution. This is a security feature :)
You could of course change that in your own implementation.

**Comment by ottokruse** [comment]
Closing for now, let us know if you have further questions
