### ISSUE TITLE
Magic Link user not found email manipulation - domain extraction

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/amazon-cognito-passwordless-auth#69]
Per this snippet:

https://github.com/aws-samples/amazon-cognito-passwordless-auth/blob/6e1bfa8e28cd2145d0f5c3d3b0ecd3a3f3573123/cdk/custom-auth/magic-link.ts#L131-L137

Were not sure what testing has been done here but in observation and limited testing it possibly not going work all cases:

The `domain` extraction if understood correctly given the `email` reconstruction `${name}@${domain}.***`, is attempting to just get the root domain and any subdomains, but not TLD/public suffix parts? the slice(1,6) seem out of place?   

Whist it understood that the attempt here is to have a fully self-contained implementation there seems to be maintained TLD/public suffix list like [here](https://github.com/publicsuffix/list) and more specifically [here](https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat) as used by [this](https://github.com/remusao/tldts) url parser.

**Comment by ottokruse** [comment]
That piece of code is related to user enumeration prevention. It basically returns a bogus email address, that will be masked.

The story is that when requesting a magic link we return the masked e-mail address in the public challenge parameters. This is nice so the user knows where the magic link is sent to (in case the user does not sign-in with magic link but e.g. with usernme). Unfortunately this opens the door for user enumeration (when the user pool is configured with preventUserExistenceErrors=true). Which is why we mask the e-mail addresses.

The code you pasted comes into play when a non-existant user signs in. To prevent user enumeration Cognito will appear to proceed with the sign-in (event though it will never work) and calls the custom auth lambda with `event.request.userNotFound = true`. In that case we don't have an e-mail address to mask and return to public challenge parameters, so we use the fake username to create a dummy e-mail address.

Now that I explained this to you I think we should remove sending back the e-mail address if the user pool is configured with preventUserExistenceErrors=true.

**Comment by ottokruse** [comment]
We have gotten rid of sending back the email address as public challenge parameter in #134
