### ISSUE TITLE
End-to-End Example: PassKey on other device fails

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/amazon-cognito-passwordless-auth#71]
All deployed per [instructions](https://github.com/aws-samples/amazon-cognito-passwordless-auth/tree/main/end-to-end-example)

Running on MacOS, and using an iPhone. and already set up "sign in with Face or Touch":
![Screenshot 2023-08-06 at 3 26 08 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/01898ac6-ceaa-4cc7-b13e-01854a084818)

If one log logs in, and then attempt to "Register New Authenticator":

![Screenshot 2023-08-06 at 3 14 27 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/701528d1-d3e3-4ecd-bcde-0afa3a8e1bbf)

And Selects "Other Options":
![Screenshot 2023-08-06 at 3 15 47 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/a7308fcb-7d00-4a89-ae8c-a4205e134ab2)

and Chooses "iPhone, iPad or Android Device", on cease presented with a QR code (I messed with it so it won't work):
![Screenshot 2023-08-06 at 3 16 30 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/fa49a42d-1e50-4df0-bfd2-1feb2edb015a)

And once uses one phone to scan and add the passkey (per following instructions) it results in and "Operation Failed":
![Screenshot 2023-08-06 at 3 18 02 PM](https://github.com/aws-samples/amazon-cognito-passwordless-auth/assets/66816457/b7f785d6-676f-4cf4-9ac4-d42a808f5e75)

Not sure where to look to see what the error is, we're not seeing anything in the various Lambda logs.

**Comment by ottokruse** [comment]
Ah so you are trying to register a credential that is already registered? You can only register a passkey once. So if you added your phone already, adding it again will lead to an error.

Unfortunately, WebAuthn being new as it is, error messages from the browser aren't always the most obvious.

I recommend to use Chrome for testing - you might see a more revealing error message there.

Your iOS version is recent and shouldn't be the issue.

**Comment by ottokruse** [comment]
Ok sure, cool.

> Whilst I get that you are trying to not have any package dependencies, for real use cases "in the wild" this aspect probably need to be a full (to spec) implementation.

I believe we implement the minimum required set of features (register FIDO2 credentials and sign in with them) that would cover most "in the wild" needs, but happy to corrected otherwise if you can point us to some concrete things that are missing. Would be great to add those features in that case to this sample

The only notable thing that comes to mind right now that is not covered in this sample, is dealing with [attestation](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Attestation.html). But most online services that want to use FIDO2 sign in won't verify attestations. It's a feature for Enterprises that e.g. want to limit the types of authenticators used to their whitelisted ones. Therefore, in the current philosophy of this sample, not worth the development effort to add to this sample.

**Comment by ottokruse** [comment]
> its been a while and hope this follow up is well received, as intentions are along the lines of help you, help us, and am in no position to offer corrections!

Sure thing @Simonl9l ! Appreciate your questions and feedback.

I've come across Mathew's stuff (follow him on mastodon) and have seen his sites/libs, and they surely look very helpful.

> Of note I've been using this on the client side package, with the preference to use C# and [FIDO2.Net ](https://fido2-net-lib.passwordless.dev/)on the servers side (native AoT compilation for efficiency) so far successfully, and have implementations of the Cognito Triggers using this package.

Nice! It's great there are multiple WebAuthn examples and implementations out there, so that our customers and everyone, have something to choose from, and can compare "how do they do it".
