### ISSUE TITLE
Question: Automating Sign Up process to trigger Magic Link Sign In

### ISSUE THREAD

**Issue by fkwfung** [aws-samples/amazon-cognito-passwordless-auth#96]
Hello @ottokruse ,

Upon reviewing the ``Passwordless`` stack documentation and client library, it appears that the Sign Up flow will be handled separately. To meet the business requirements, we will need to customize and implement our own Sign Up flow accordingly.

Once a new user onboards, the plan is to utilize the Magic Link Sign In flow as designed in the Passwordless stack. To achieve this, we will deploy an API Gateway with user sign up implementation. In order to trigger the sending of an email with a Magic Link to the user, the following steps will be taken:

1) ``AdminCreateUserCommand``: to create a new user at Cognito

2) ``AdminInitiateAuthCommand``: to initiate the custom auth flow

3) ``AdminRespondToAuthChallengeCommand``: to respond with ClientMetadata setting to ``signInMethod: "MAGIC_LINK"``

4) Email to be sent newly onboard user with a Redirect URL to sign in

Regarding the onboarding flow, we appreciate your assistance in providing advice for bundling. We would also like to evaluate the duration of the Lambda function triggered from the API Gateway:
1) First trigger (Init) or Cold start
```
Duration: 3911.69 ms Billed Duration: 3912 ms Memory Size: 256 MB Max Memory Used: 103 MB Init Duration: 714.09 ms
Duration: 3954.84 ms Billed Duration: 3955 ms Memory Size: 256 MB Max Memory Used: 103 MB Init Duration: 719.79 ms
```

2) Subsequent triggers (Hot)
```
Duration: 2068.67 ms Billed Duration: 2069 ms Memory Size: 256 MB Max Memory Used: 104 MB
Duration: 813.12 ms Billed Duration: 814 ms Memory Size: 256 MB Max Memory Used: 104 MB
Duration: 2243.66 ms Billed Duration: 2244 ms Memory Size: 256 MB Max Memory Used: 104 MB
```

I would appreciate your advice on whether reusing the Magic Link from ``Passwordless`` stack for onboarding is the correct approach giving the Lambda to ``await`` the response from using admin functions to interact with Cognito. From a technical standpoint, your guidance would be valuable.

Thank you,

Frankie

**Comment by ottokruse** [comment]
Hi Frankie!

Thanks for detailing it out.

First off, I had a discussion with another user about auto sign-up in #92 and you probably want to read through that entire thread––there's an alternate approach in there to implement the auto-signUp flow, that saves you implementing the custom API. If you can I would choose this way.

I guess the thing is, of the user is alreay signed up, you would just want to initAuth from the frontend right, no need for your API. You only need your API because you want to auto sign up in case it is needed?

Be that as it may, your custom API approach, that can also work. What you're describing, the sequence of events 1-4, and the use of admin methods, makes sense to me. There's choices to make, e.g. you don't need to do it all synchronously and have the user wait for it. You could e.g. return HTTP 200 already after putting a message onto SQS and then do step 1, 2 and 3 asynchronously in the backend after receiving the SQS message (besides SQS you could also do an async lambda invocation, a step function would also be nice, event bridge, there's many options really).

Reason for the long response times in your case might be because you see multiple cold starts added together:

1. cold start for the Lambda that implements the API
2. cold start for the Define Auth Cognito Lambda trigger
3. cold start for the Create Auth  Cognito Lambda trigger
4. cold start for the Verify Auth  Cognito Lambda trigger

Now under normal load a user wouldn't in all likelihood hit ALL cold starts unless (s)he's very unlucky. But if you're testing as a dev with little load it might happen.

**Comment by ottokruse** [comment]
Another user suggested to use one and the same Lambda function for Define Auth, Create Auth and Verify Auth to reduce cold starts and that's an interesting angle as well: #28 

Logs would all land in the same log group though, which is why we're not opting for it by default.

**Comment by fkwfung** [comment]
Hi Otto, 

Thank you for your advice. Had checked on #92 and that will be nice for a single web application interacting with Cognito. 
We are trying to build the Passwordless services on Cognito to support multiple web applications or even mobile apps. The API Gateway approach will be more suitable in order to build business logics on gating and controls over user sign up process.

Agree with you on asynchronous approaches in handling the rest of initiating auth. I will implement that and be mindful of rate limit on Cognito requests.

**Comment by ottokruse** [comment]
Ok sure.

If you go that way, you could use a client secret, to force all Cognito calls to be made from the backend (where you can make the secret securely available) and not frontend (that won't have the secret).

Also, recommend to use AWS WAF with rate limit rule for individual IPs, it's a GREAT way to make public APIs pretty resilient against (D)DOS attacks (intended or not). See these examples: https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based-examples.html

**Comment by ottokruse** [comment]
Closing this one now.

FYI In #131 there is a discussion for adding automatic user registration
